#!/bin/bash

# Export ENV variables
#
dotenv () {
  echo "Loading... ENV variables from $1"
  if [ ! -f $1 ]; then
    echo "Error: File $1 must exist!" >&2
    exit 1
  fi

  CURRENT_ENV_FILE=$1

  set -a
  source $CURRENT_ENV_FILE
  set +a
}
